# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_Dead',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(editable=False),
        ),
    ]
