# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_auto_20170629_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='BC_Date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(help_text='if You Check the BC Date field please enter the BC year'),
        ),
    ]
