# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=700)),
                ('DateOfCreation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('Picture', models.FileField(upload_to='')),
                ('Job', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Publish_Time', models.DateTimeField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Company')),
                ('authur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Person')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.genre')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Person'),
        ),
    ]
