# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America'), ('Australia', 'Australia'), ('Europe', 'Europe'), ('Africa', 'Africa')], max_length=1000),
        ),
    ]
