# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('posts', '0003_auto_20170627_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='Bio',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Interest_Fields',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='person',
            name='Major',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Jobs'),
        ),
    ]
