# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170627_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Picture',
        ),
        migrations.AddField(
            model_name='person',
            name='PictureFile',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='PictureUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
