# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170627_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='PictureUrl',
        ),
    ]
