# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('posts', '0006_remove_person_pictureurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('PictureFile', models.ImageField(upload_to='')),
                ('Bio', ckeditor.fields.RichTextField()),
                ('Major', models.CharField(max_length=10000)),
                ('Interest_Fields', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Country')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Manager'),
        ),
    ]
