# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170629_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='First_Display',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
