# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_first_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='Complete_Text',
        ),
    ]
