# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('Company', models.CharField(max_length=30)),
                ('About', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Company', models.CharField(max_length=35)),
                ('Price', models.IntegerField()),
                ('Year', models.CharField(max_length=4)),
                ('Aboutit', models.CharField(max_length=1000000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Group')),
            ],
        ),
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneynow', models.IntegerField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
