# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='About',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='Aboutit',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
