# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170625_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ItemGroup',
        ),
    ]
