# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170625_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_VIP',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
