# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Publish_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
