# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('program_title', models.CharField(max_length=250)),
                ('Logo', models.FileField(upload_to='')),
                ('price', models.FloatField(max_length=100)),
                ('codeprice', models.FloatField(max_length=200)),
                ('text', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('Company', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programseries.Program_Serie'),
        ),
    ]
