# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=1000000),
        ),
    ]
