# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('type', models.CharField(max_length=26)),
                ('log', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='programlanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_Name', models.CharField(max_length=20)),
                ('Logo', models.FileField(upload_to='')),
                ('Country', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachprogramming.programlanguages'),
        ),
    ]
