# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachprogramming', '0003_auto_20170625_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlanguages',
            name='text',
        ),
    ]
