# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachprogramming', '0004_remove_programlanguages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlanguages',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
